version: '3'

services:
  node:
    image: node:latest
    container_name: api_node
    working_dir: /opt/api
    volumes:
      - ./src:/opt/api
      - ./config.js:/opt/api/config.js
    environment:
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - TOKEN_EXPIRE=${TOKEN_EXPIRE}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_URL=mongo:27017
    ports:
      - 8877:${PORT}
    links:
      - mongo
    tty: true
    command:
      sh -c 'npm init --force && npm i -S create-rest-api && node index.js'

  mongo:
    image: mongo:latest
    container_name: api_mongo
    volumes:
      - ./data:/data/db
    command: mongod --smallfiles
