version: '3'

services:
  node:
    image: node:latest
    container_name: api_node
    working_dir: /opt/api
    restart: unless-stopped
    volumes:
      - ./src:/opt/api
      - ./config.js:/opt/api/config.js
    environment:
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - TOKEN_EXPIRE=${TOKEN_EXPIRE}
      - DB_CLIENT=postgres
      - DB_HOST=api_postgresql
      - DB_PORT=5432
      - DB_USER=api
      - DB_PASSWORD=apiPass
      - DB_NAME=api
    ports:
      - 8877:${PORT}
    links:
      - api_postgresql
    tty: true
    command:
      sh -c 'npm init --force && npm i -S api-i && node index.js'

  postgresql:
    image: postgres:latest
    container_name: api_postgresql
    restart: unless-stopped
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      - ./data/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=apiPass
      - POSTGRES_DB=api
